package com.picture.business.model;

import com.springboot.simple.jdbc.model.BaseModel;

import java.util.Date;

public class ImageModel extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.create_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.modified_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.deleted
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.access_key
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.upload_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.file_name
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.file_path
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.file_size
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.focus
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Boolean focus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.id
     *
     * @return the value of t_image.id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.id
     *
     * @param id the value for t_image.id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.create_time
     *
     * @return the value of t_image.create_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.create_time
     *
     * @param createTime the value for t_image.create_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.modified_time
     *
     * @return the value of t_image.modified_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.modified_time
     *
     * @param modifiedTime the value for t_image.modified_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.deleted
     *
     * @return the value of t_image.deleted
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.deleted
     *
     * @param deleted the value for t_image.deleted
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.access_key
     *
     * @return the value of t_image.access_key
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.access_key
     *
     * @param accessKey the value for t_image.access_key
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setAccessKey(Long accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.upload_time
     *
     * @return the value of t_image.upload_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.upload_time
     *
     * @param uploadTime the value for t_image.upload_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.file_name
     *
     * @return the value of t_image.file_name
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.file_name
     *
     * @param fileName the value for t_image.file_name
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.file_path
     *
     * @return the value of t_image.file_path
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.file_path
     *
     * @param filePath the value for t_image.file_path
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.file_size
     *
     * @return the value of t_image.file_size
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.file_size
     *
     * @param fileSize the value for t_image.file_size
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.focus
     *
     * @return the value of t_image.focus
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Boolean getFocus() {
        return focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.focus
     *
     * @param focus the value for t_image.focus
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setFocus(Boolean focus) {
        this.focus = focus;
    }
}