package com.picture.business.model;

import com.springboot.simple.jdbc.model.BaseModel;

import java.util.Date;

public class TagImageModel extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.create_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.modified_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.deleted
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.access_key
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.tag_id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_image.image_id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    private Long imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.id
     *
     * @return the value of t_tag_image.id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.id
     *
     * @param id the value for t_tag_image.id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.create_time
     *
     * @return the value of t_tag_image.create_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.create_time
     *
     * @param createTime the value for t_tag_image.create_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.modified_time
     *
     * @return the value of t_tag_image.modified_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.modified_time
     *
     * @param modifiedTime the value for t_tag_image.modified_time
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.deleted
     *
     * @return the value of t_tag_image.deleted
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.deleted
     *
     * @param deleted the value for t_tag_image.deleted
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.access_key
     *
     * @return the value of t_tag_image.access_key
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.access_key
     *
     * @param accessKey the value for t_tag_image.access_key
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setAccessKey(Long accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.tag_id
     *
     * @return the value of t_tag_image.tag_id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.tag_id
     *
     * @param tagId the value for t_tag_image.tag_id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_image.image_id
     *
     * @return the value of t_tag_image.image_id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_image.image_id
     *
     * @param imageId the value for t_tag_image.image_id
     *
     * @mbggenerated Mon Mar 08 10:43:12 CST 2021
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }
}