package com.picture.business.model;

import com.springboot.simple.jdbc.model.BaseModel;

import java.util.Date;

public class TagModel extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.id
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.create_time
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.modified_time
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.deleted
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.access_key
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    private Long accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.tag_name
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    private String tagName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.id
     *
     * @return the value of t_tag.id
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.id
     *
     * @param id the value for t_tag.id
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.create_time
     *
     * @return the value of t_tag.create_time
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.create_time
     *
     * @param createTime the value for t_tag.create_time
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.modified_time
     *
     * @return the value of t_tag.modified_time
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.modified_time
     *
     * @param modifiedTime the value for t_tag.modified_time
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.deleted
     *
     * @return the value of t_tag.deleted
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.deleted
     *
     * @param deleted the value for t_tag.deleted
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.access_key
     *
     * @return the value of t_tag.access_key
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public Long getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.access_key
     *
     * @param accessKey the value for t_tag.access_key
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public void setAccessKey(Long accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.tag_name
     *
     * @return the value of t_tag.tag_name
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.tag_name
     *
     * @param tagName the value for t_tag.tag_name
     *
     * @mbggenerated Sat Feb 20 19:45:09 CST 2021
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }
}